version: "3"

services:
  server:
    image: example/server:1.0.0
    build:
      context: ./server
    ports:
      - 50051:50051

  client:
    image: example/client:1.0.0
    build:
      context: ./client
    ports:
      - 9000:9000

  proxy:
    image: envoyproxy/envoy-dev:158535979a833d076c44c701f1cdf5406187d3ba
    ports:
      - "9901:9901"
      - "10000:10000"
    volumes:
      - ./proxy/envoy.yaml:/etc/envoy/envoy.yaml
