version: "3"

services:
  server:
    image: example/server:1.0.0
    build:
      context: ./server
    ports:
      - 50051:50051

  client:
    image: example/client:1.0.0
    build:
      context: ./client
    ports:
      - 9000:9000
    extra_hosts:
      - "host.docker.internal:host-gateway"

  proxy:
    image: example/proxy:1.0.0
    build:
      context: ./proxy
    ports:
      - "9901:9901"
      - "10000:10000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./proxy/envoy.yaml:/etc/envoy/envoy.yaml
